const moneyActionTypes = {
  GET_ITEMS: 'GET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
  CLEAR_CURRENT_ITEM: 'CLEAR_CURRENT_ITEM',
  CLEAR_ITEMS: 'CLEAR_ITEMS',
  UPDATE_ITEM: 'UPDATE_ITEM',
  FILTER_ITEM: 'FILTER_ITEM',
  CLEAR_FILTER: 'CLEAR_FILTER',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',
};

export default moneyActionTypes;
